### ISSUE TITLE
Cleanup swissmedic_* files after creation

### ISSUE THREAD

**Issue by col-panic** [zdavatz/oddb2xml#13]
oddb2xml leaves a number of files lying around like

-rw-r--r-- 1 jenkins jenkins    303093 May  8 09:00 swissmedic_fridge.xlsx
-rw-r--r-- 1 jenkins jenkins    303093 May 22 12:54 swissmedic_fridge.xlsx.1
-rw-r--r-- 1 jenkins jenkins    303093 May 24 06:37 swissmedic_fridge.xlsx.2
-rw-r--r-- 1 jenkins jenkins    303093 May 31 06:38 swissmedic_fridge.xlsx.3
-rw-r--r-- 1 jenkins jenkins    303093 Jun  3 13:05 swissmedic_fridge.xlsx.4
-rw-r--r-- 1 jenkins jenkins    303017 Jun  7 06:38 swissmedic_fridge.xlsx.5
-rw-r--r-- 1 jenkins jenkins    303017 Jun 14 06:38 swissmedic_fridge.xlsx.6
-rw-r--r-- 1 jenkins jenkins    303017 Jun 18 10:42 swissmedic_fridge.xlsx.7
-rw-r--r-- 1 jenkins jenkins    311738 May  8 09:00 swissmedic_orphan.xlsx
-rw-r--r-- 1 jenkins jenkins    311738 May 22 12:54 swissmedic_orphan.xlsx.1
-rw-r--r-- 1 jenkins jenkins    311738 May 24 06:37 swissmedic_orphan.xlsx.2
-rw-r--r-- 1 jenkins jenkins    311738 May 31 06:38 swissmedic_orphan.xlsx.3
-rw-r--r-- 1 jenkins jenkins    313609 Jun  3 13:05 swissmedic_orphan.xlsx.4
-rw-r--r-- 1 jenkins jenkins    313609 Jun  7 06:38 swissmedic_orphan.xlsx.5
-rw-r--r-- 1 jenkins jenkins    313609 Jun 14 06:38 swissmedic_orphan.xlsx.6
-rw-r--r-- 1 jenkins jenkins    313609 Jun 18 10:42 swissmedic_orphan.xlsx.7
-rw-r--r-- 1 jenkins jenkins   2647558 May  8 09:01 swissmedic_package.xlsx
-rw-r--r-- 1 jenkins jenkins   2674914 May 22 12:54 swissmedic_package.xlsx.1
-rw-r--r-- 1 jenkins jenkins   2674914 May 24 06:37 swissmedic_package.xlsx.2
-rw-r--r-- 1 jenkins jenkins   2674914 May 31 06:38 swissmedic_package.xlsx.3
-rw-r--r-- 1 jenkins jenkins   2674914 Jun  3 13:05 swissmedic_package.xlsx.4
-rw-r--r-- 1 jenkins jenkins   2674914 Jun  7 06:38 swissmedic_package.xlsx.5
-rw-r--r-- 1 jenkins jenkins   2672681 Jun 14 06:38 swissmedic_package.xlsx.6
-rw-r--r-- 1 jenkins jenkins   2672681 Jun 18 10:43 swissmedic_package.xlsx.7

could you provide a clean option for removing them automatically after the result was generated? 

thanks

**Comment by zdavatz** [comment]
seems like this is done with the latest version.
