### ISSUE TITLE
Invalid entry in article.xml

### ISSUE THREAD

**Issue by col-panic** [zdavatz/oddb2xml#17]
Thats an invalid entry, no?

```
3739614   <ART DT="">
3739615     <REF_DATA>0</REF_DATA>
3739616     <PHAR>8808827</PHAR>
3739617     <SALECD>I</SALECD>
3739618     <DSCRD> 237.44                                           </DSCRD>
3739619     <DSCRF> 237.44                                           </DSCRF>
3739620     <SORTD> 237.44                                           </SORTD>
3739621     <SORTF> 237.44                                           </SORTF>
3739622     <ARTCOMP/>
3739623   </ART>
```

**Comment by zdavatz** [comment]
this article is not active. Seems like garbage coming from Refdata.

**Comment by zdavatz** [comment]
This is data coming from the IGM-11 file from zur Rose. This is not an invalid entry from our part.

**Comment by ngiger** [comment]
grep 8808827 data/zurrose_transfer.dat 
returns
1128808827 237.44                                           0237440373350000000000000000000000002
Name is really " 237.44                                           "

**Comment by zdavatz** [comment]
Das ist eigentlich "Allround Finespray Zerstäuberpumpe 50 ml 100 Stk. Weiss" von "DR. BURKARD KREYENBÜHL  APOTHEKE". Wahrscheinlich eine Magistralität.

Wurde aber falsch eingepflegt....

**Comment by col-panic** [comment]
Ok im Satz ist es noch drinnen. Aber der Fehler liegt bei mir, weil ich inaktive medis aufnehme! Ich hab das mal intern zur klärung gestellt! merci!

**Comment by zdavatz** [comment]
Das muss Apotheke zur Rose korrigieren. Sie haben es bereits aufgenommen.
