### ISSUE TITLE
Homöopatahische Mittel gemäss Kapitel 70 fehlen im oddb2xml

### ISSUE THREAD

**Issue by ngiger** [zdavatz/oddb2xml#22]
Bei Elexis wurden Rechnungen zurückgewiesen, Gemäss Julian Kappis aus folgenden Gründen:

* Zusätzlich zur offiziellen Spezialitätenliste existiert das sogenannte Kapitel 70 (http://bag.e-mediat.net/Sl2007.web.external/varia_De.htm)
* Darauf sind homöopathische Medikamente (mit Pharmacode) verzeichnet, welche von den Kassen bezahlt werden

Anforderung:

* oddb2xml --artikelstamm muss diese entsprechend berücksichtigten und auch als SL Medikamente markieren

**Comment by ngiger** [comment]
S.a. https://redmine.medelexis.ch/issues/14347

Bemerkungen:

* HTML wäre einfach zu parsen, bis auf
* Limitationen, wo das Format uneinheitlich ist
* Korrekte Lösung wäre BAG/refdata nimmt diese Informationen in rafdata_pharma.xml auf

**Comment by zdavatz** [comment]
Kannst Du bitte ein paar Beispiele von Produkten geben, welche fehlen sollen. Dann haben wir ein paar Beispiele.

**Comment by ngiger** [comment]
Beispiel ist. Daten kommen aus zur Rose.dat

    1122069562EINF ARZNEI Urtinktur 1-10g/ml                    0010040013401000000000025000005884712

Und ergeben im artikelstamm_01082018_v5.xml


        <ITEM PHARMATYPE="N">
            <GTIN>2500000588471</GTIN>
            <PHAR>2069562</PHAR>
            <SALECD>A</SALECD>
            <DSCR>EINF ARZNEI Urtinktur 1-10g/ml</DSCR>
            <DSCRF>--missing--</DSCRF>
            <PEXF>10.04</PEXF>
            <PPUB>13.40</PPUB>
        </ITEM>

**Comment by zdavatz** [comment]
Sind diese Daten im _RefdataPharma.xml_ nicht vorhanden?

**Comment by ngiger** [comment]
Nein. Via grep -ri urtinktur downloads/refdata_*Pharma.xml  finde ich nix. Dito für 3 weiter Arikel daraus.

**Comment by zdavatz** [comment]
Ok, dann werde ich das an der nächsten Refdata Sitzung vorbringen.

**Comment by zdavatz** [comment]
Diese Artikel müssten eigentlich im _RefdataPharma.xml_ vorhanden sein.

**Comment by ngiger** [comment]
Wann ist die nächste Refdata-Sitzung?

**Comment by zdavatz** [comment]
19.9.2018

**Comment by zdavatz** [comment]
Siehe Email an das Sekretariat der Refdata: https://ywesee.slack.com/files/U27FC8WLA/FC59MR807/70.01._homoeopathica_und_anthroposophica_nicht_bei_refdata_vorhanden__jedoch_gem__ss_bag_in_der_sl.

**Comment by ngiger** [comment]
Habe  Version 2.5.6 erstellt, welche für den Artikelstamm die Daten aus dem Kapitel 70 übernimmt.

**Comment by zdavatz** [comment]
Der SB Flag wird nicht gesetzt.

**Comment by zdavatz** [comment]
Man ist sich diesem Problem bewusst bei Refdata. Ich habe das Problem an der Sitzung vom 19.9.2018 thematisiert. Interessant ist, dass die "Produkte" auch einen inoffiziellen GTIN haben. Es aber keine "Produkte" sondern Produktegruppen.

**Comment by ngiger** [comment]
Kannst Du die Liste dieser GTINs erhalten? Erscheinen diese GTIN irgendwo auf den Packungen?

**Comment by zdavatz** [comment]
Die GTINs sind nur im Transfer.dat via Pharmacode auffindbar.

**Comment by zdavatz** [comment]
Siehe auch: https://ywesee.slack.com/archives/C37QM70MA/p1537429142000100

**Comment by zdavatz** [comment]
Das PDF von HCI: https://github.com/zdavatz/oddb2xml/issues/26#issuecomment-424243917
