### ISSUE TITLE
Swissmedic hat neuen Download URL

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb2xml#29]
Die Swissmedic hat einen neuen Download-URL: https://www.swissmedic.ch/swissmedic/de/home/services/listen_neu.html#-257211596

**Comment by zdavatz** [comment]
Sieht so aus, als hätte nur der Download-Link geändert.

**Comment by ngiger** [comment]
Anpassungen gepushed und für Gem 2.6.0 vorbereitet.
Willst Du das Ganze noch bei Dir testen, before ich es release?

**Comment by zdavatz** [comment]
bitte pushen.
