### ISSUE TITLE
Swissmedic Packages reference renamed

### ISSUE THREAD

**Issue by ngiger** [zdavatz/oddb2xml#30]
Under https://www.swissmedic.ch/swissmedic/de/home/services/listen_neu.html
the link  "Zugelassene Verpackungen" was renamed  to "Zugelassene Packungen".

Fix will follow soon

**Comment by zdavatz** [comment]
Interesting. Our Bash-Script of yesterday already used "Packungen". https://github.com/zdavatz/cpp2sqlite/blob/master/scripts/download.sh#L26

**Comment by ngiger** [comment]
Dann hat dieses Script aber einen Fehler. Der volle Name ist nämlicht
FILE1="https://www.swissmedic.ch/dam/swissmedic/de/dokumente/internetlisten/zugelassene_packungen_ham.xlsx.download.xlsx/Zugelassene_Packungen%20HAM_31012019.xlsx"
d.h. Es wird immer die Datei vom 31.01.2019 runter geladen.
Deshalb suche ich nach einem Link mit dem Text "Zugelassene Packungen" und hole mir dann das Attribut href draus.

**Comment by zdavatz** [comment]
Danke für die Info!

**Comment by zdavatz** [comment]
Gemäss der Swissmedic sollte dieser URL auch immer gehen: https://www.swissmedic.ch/dam/swissmedic/de/dokumente/listen/excel-version_zugelasseneverpackungen.xlsx.download.xlsx/excel-version_zugelasseneverpackungen.xlsx

**Comment by zdavatz** [comment]
Und diese URL wird gemäss der Swissmedic auch immer gehen: https://www.swissmedic.ch/dam/swissmedic/de/dokumente/internetlisten/zugelassene_packungen_ham.xlsx

**Comment by ngiger** [comment]
Werde ich nächste Woche anschauen und in eine neue Version einfliessen lassen. Diese Links gefallen mir deutlich besser.

**Comment by zdavatz** [comment]
gemäss Email von Lukas Jaggi, Swissmedic. https://slack-files.com/T27F6280H-FGKB7922G-7a0f24631d

**Comment by ngiger** [comment]
Alte Links werden auch in Zukunft unterstützt. Deshalb nix zu ändern
