### ISSUE TITLE
Artikelstamm: Wrong ATC for 'BRONCHO-VAXOM Kaps Erw 10 Stk' code taken from redata instead of swissmedic packages

### ISSUE THREAD

**Issue by ngiger** [zdavatz/oddb2xml#32]
A medical practice reported the following errors
<pre>
Die Medikamente:
BRONCHO-VAXOM Kaps. Erw 10 Stk, BRONCHO-VAXOM Kaps. Erw 30 Stk, BRONCHO-VAXOM Kaps. Kind10 Stk sowie BRONCHO-VAXOM Kaps. Kind 30 Stk rufen im Elexis jeweils die Impfliste auf und machen einen entsprechenden Eintrag, jedoch sind diese Medikamente KEINE Impfstoffe!
</pre>
Reason is that refdata_pharma contains the wrong ATC-Code J07AX

      <ITEM DT="2019-04-08T00:00:00">
        <ATYPE>PHARMA</ATYPE>
        <GTIN>7680005960016</GTIN>
        <PHAR>0829684</PHAR>
        <SWMC_AUTHNR>00596001</SWMC_AUTHNR>
        <NAME_DE>BRONCHO-VAXOM Kaps Erw 10 Stk</NAME_DE>
        <NAME_FR>BRONCHO-VAXOM caps adult 10 pce</NAME_FR>
        <ATC>J07AX</ATC>
        <AUTH_HOLDER_NAME>OM Pharma SA</AUTH_HOLDER_NAME>
        <AU

Whereas in the swissmedic-packages we find the correct value ATC-Code R07AX
<pre>
596,1,"Broncho-Vaxom adultes, capsules","OM Pharma SA","Bakterien- und Hefepräparate",03.05.0.,R07AX,1997/07/03,1997/07/03,2022/07/03,1,10,Kapsel(n),D,D,D,"haemophili influenzae lysatum, diplococci pneumoniae lysatum, klebsiellae pneumoniae et ozaenae lysatum, staphylococci aurei lysatum, streptococci pyogen. et viridantis lysatum, neisseriae catarrhalis lysatum","lysatum bacteriorum lyophilisatum 7 mg corresp. haemophili influenzae lysatum et diplococci pneumoniae lysatum et klebsiellae pneumoniae et ozaenae lysatum et staphylococci aurei lysatum et streptococci pyogen. et viridantis lysatum et neisseriae catarrhalis lysatum, natrii hydrogenoglutamas, antiox.: E 310, color.: E 132, excipiens pro capsula.",,"immuno-stimulant lors d' infections du système respiratoire et lors de bronchite chronique",,,,
</pre>

https://ch.oddb.org/de/gcc/search/zone/drugs/search_query/00596/search_type/st_registration
shows the correct ATC-Code R07AX

**Comment by zdavatz** [comment]
Melde ich gleich der Refdata.

**Comment by zdavatz** [comment]
https://slack-files.com/T27F6280H-FHSATN8CA-cea0376b79

**Comment by zdavatz** [comment]
https://amiko.oddb.org/de/fi?gtin=7680005960016&type=title&key=broncho-vaxom

**Comment by zdavatz** [comment]
Ich gehe davon aus, dass die FI korrekt ist.

**Comment by ngiger** [comment]
https://ch.oddb.org/de/gcc/fachinfo/reg/00667 wird der ATC-Code mit R07AX angegeben, wie in refdata, aber swissmedic-packages sagt J07AX. Was für ein Puff! Und bis jetzt hat oddb2xml noch nie die Fachinfos geparsed, um etwas daraus zu lesen, was kompliziert wird.

**Comment by ngiger** [comment]
Folgende Unterschiedlichen ATC-Codes gefunden

<pre>
WARNING: ATC differs from refdata J07AX and swissmedic R07AX for 0059601 Broncho-Vaxom adultes, capsules
WARNING: ATC differs from refdata J07AX and swissmedic R07AX for 0059701 Broncho-Vaxom enfants, capsules
WARNING: ATC differs from refdata A02AD01 and swissmedic A02AC10 for 0857101 Rennie Peppermint, Lutschtabletten
WARNING: ATC differs from refdata A03AX13 and swissmedic A02X for 0890901 LUVOS Heilerde Ultra innerlich Plv 380 g
WARNING: ATC differs from refdata A03AX13 and swissmedic A02X for 0891001 LUVOS Heilerde 1 innerlich Plv 480 g
WARNING: ATC differs from refdata C01EB04 and swissmedic C01EX for 1002902 ZELLER Herz und Nerven Tropfen Fl 100 ml
WARNING: ATC differs from refdata D11AF and swissmedic D02AF for 1037902 Lebewohl, Hühneraugenpflaster
WARNING: ATC differs from refdata A06AB06 and swissmedic A06AB56 for 1056701 MIDRO Tee 80 g
WARNING: ATC differs from refdata A02AA04 and swissmedic A06AD02 for 1057401 MAGNESIA S PELLEGRIN Plv o Aroma 70 g
WARNING: ATC differs from refdata D05AA and swissmedic D03 for 1156501 LEUCEN Zugsalbe Tb 30 g
WARNING: ATC differs from refdata A01AD11 and swissmedic D03AX03 for 1330801 BEPANTHEN Lös 5 % Fl 100 ml
WARNING: ATC differs from refdata D08AL30 and swissmedic D03AX for 1335803 WUNDSALBE Widmer Tb 20 g
WARNING: ATC differs from refdata A06AB06 and swissmedic A06AB56 for 1532201 Midro Tabs, Tabletten
WARNING: ATC differs from refdata A02AD01 and swissmedic A02AC10 for 1837001 Zeller Magen, Kautabletten
WARNING: ATC differs from refdata R06AE55 and swissmedic A04A for 1838301 Itinerol B6, suppositoires pour adultes et adolescents
WARNING: ATC differs from refdata R06AE55 and swissmedic A04A for 1838302 Itinerol B6, suppositoires pour enfants
WARNING: ATC differs from refdata A06AX02 and swissmedic A06AB for 2110901 Lecicarbon, Suppositorien für Erwachsene
WARNING: ATC differs from refdata A06AX02 and swissmedic A06AB for 2110902 Lecicarbon, Suppositorien für Kinder
WARNING: ATC differs from refdata D11AF and swissmedic D02AF for 2342001 LEBEWOHL liq Fl 10 ml
WARNING: ATC differs from refdata R06AE55 and swissmedic A04A for 2356001 Itinerol B6, suppositoires pour bébés et enfants
WARNING: ATC differs from refdata A06AC55 and swissmedic A06AB56 for 2474902 VOGEL Linoforce Gran Ds 70 g
WARNING: ATC differs from refdata A01AD11 and swissmedic D04AB for 2516401 BENZOCAINE PD Paste Tb 8 g
WARNING: ATC differs from refdata A16AX99 and swissmedic A05AX for 2526501 SCHOENENBERGER Löwenzahn Heilpflanzensaft 200 ml
WARNING: ATC differs from refdata R05C and swissmedic R05CA for 2527301 SCHOENENBERGER Thymian Heilpflanzensaft 200 ml
WARNING: ATC differs from refdata S01GA51 and swissmedic S01XA for 2594204 OCULOSAN Gtt Opht 10 ml
WARNING: ATC differs from refdata A11EX and swissmedic A13A for 2631001 STRATH Rekonvaleszenz Tropfen 100 ml
WARNING: ATC differs from refdata A06AC51 and swissmedic A06AB56 for 2682101 Agiolax Gran
WARNING: ATC differs from refdata A01AA03 and swissmedic A01AA51 for 2692401 ELMEX fluid Lös 50 ml
WARNING: ATC differs from refdata A02AA04 and swissmedic A06AD02 for 2748101 MAGNESIA S PELLEGRIN Brause Plv o Aroma 125 g
WARNING: ATC differs from refdata A02AA04 and swissmedic A06AD02 for 2748102 MAGNESIA S PELLEGRIN Brause Plv Anis 125 g
WARNING: ATC differs from refdata A11AB and swissmedic A11AA03 for 2793601 Pharmaton Vital Geriavit, Kapsel
WARNING: ATC differs from refdata L04AX03 and swissmedic L01BA01 for 2854101 Methotrexat Pfizer Tabl 2.500 mg
WARNING: ATC differs from refdata D11AF and swissmedic D02AF for 2916701 Clabin Lös
WARNING: ATC differs from refdata A12AA20 and swissmedic A12AA06 for 3108703 Calcium Sandoz 500, Brausetabletten
WARNING: ATC differs from refdata A12AA20 and swissmedic A12AA06 for 3108704 Calcium Sandoz 1000, Brausetabletten
WARNING: ATC differs from refdata M09AB03 and swissmedic B06AA11 for 3145104 Traumanase Forte Drag
WARNING: ATC differs from refdata A12AX and swissmedic A11GB01 for 3220901 Callimon, Brausetabletten
WARNING: ATC differs from refdata C05BA53 and swissmedic D03AX for 3274701 Contractubex Gel
WARNING: ATC differs from refdata N02BA65 and swissmedic N02BA51 for 3312401 Alca-C, Brausetabletten
WARNING: ATC differs from refdata C05CX03 and swissmedic C05CA for 3475502 Phlebostasin Kaps
WARNING: ATC differs from refdata A01AA03 and swissmedic A01AA51 for 3491602 ELMEX gelée Tb 25 g
WARNING: ATC differs from refdata N05CX99 and swissmedic N05CM for 3530602 Zeller Entspannung, Filmtabletten
WARNING: ATC differs from refdata B05XA02 and swissmedic B05CB04 for 3570901 Natrium bicarbonat 8,4 % B. Braun, Infusionslösung, Zusatzampullen
WARNING: ATC differs from refdata B05XA02 and swissmedic B05CB04 for 3570903 Natrium bicarbonat 1,4 % Braun, Infusionslösung
WARNING: ATC differs from refdata B03AD03 and swissmedic B03AE10 for 3618501 Fero-Folic-500, compresse a rilascio prolungato
WARNING: ATC differs from refdata R06AA02 and swissmedic N05CM for 3673601 Benocten, Tabletten
WARNING: ATC differs from refdata D03AX03 and swissmedic D11AX for 3726001 PC 30 V Lös Fl 100 ml
WARNING: ATC differs from refdata R03CC02 and swissmedic R03AC02 for 3726201 Ventolin Sirup 2 mg/5ml o Zucker
WARNING: ATC differs from refdata C05CX02 and swissmedic C05B for 3797902 Mediaven 10 mg, Filmtabletten
WARNING: ATC differs from refdata C05CX02 and swissmedic C05B for 3797903 Mediaven forte Filmtabl 30 mg
WARNING: ATC differs from refdata M02AC and swissmedic M02AX10 for 3834502 CARMOL Rheumasalbe Tb 80 g
WARNING: ATC differs from refdata D08AE04 and swissmedic V07AX for 3865802 Cremolan Waschlotion Lot
WARNING: ATC differs from refdata A11JC and swissmedic D11AX for 3870001 Pantogar, Kapseln
WARNING: ATC differs from refdata D07CB04 and swissmedic D07XB05 for 3886801 Nystalocal Creme
WARNING: ATC differs from refdata R05CA10 and swissmedic R05X for 3944502 Sidroga Erkältungstee, geschnittene Drogen
WARNING: ATC differs from refdata A01AB12 and swissmedic A01AB11 for 3979803 Drossadin Lös 0.100 %
WARNING: ATC differs from refdata A01AB12 and swissmedic A01AB11 for 3979804 Drossadin Lös 0.200 % orange
WARNING: ATC differs from refdata D02AC and swissmedic D02AX for 3990301 Excipial Creme
WARNING: ATC differs from refdata R06AE55 and swissmedic A04A for 4077001 Itinerol B6, capsules
WARNING: ATC differs from refdata M02AC and swissmedic M02AX10 for 4108003 CHINA Kopfwehöl Temple of Heaven Fl 15 ml
WARNING: ATC differs from refdata R05X and swissmedic R05FB01 for 4158803 WALA Salbei Halspastillen Box 45 g
WARNING: ATC differs from refdata R02AA20 and swissmedic R02AX for 4167901 SIDROGA Salbeiblätter 20 Btl 1 g
WARNING: ATC differs from refdata A16AX99 and swissmedic N05CM for 4168701 SIDROGA Verveine 20 Btl 1 g
WARNING: ATC differs from refdata R05DA20 and swissmedic R05FA02 for 4191902 Sanotussin, Filmtabletten
WARNING: ATC differs from refdata R06AA02 and swissmedic N05CM for 4192502 BENOCTEN Tropfen 60 mg/ml 20 ml
WARNING: ATC differs from refdata D02AC and swissmedic D11AX for 4240701 LINOLA Emuls Tb 40 g
WARNING: ATC differs from refdata D02AC and swissmedic D11AX for 4240802 Linola Fett Emuls
WARNING: ATC differs from refdata B05CA02 and swissmedic G04 for 4244101 URO-TAINER Chlorhex Spül Lös 1:5000 10 Btl 100 ml
WARNING: ATC differs from refdata A05A and swissmedic A05AX for 4262201 SCHOENENBERGER Artischock Heilpflanzensaft 200 ml
WARNING: ATC differs from refdata A01AD11 and swissmedic N01BB52 for 4266901 DENTINOX Gel Tb 25 g
WARNING: ATC differs from refdata D04AA02 and swissmedic D04AX for 4277802 PARAPIC Insektenspray 15 g
WARNING: ATC differs from refdata D01AE54 and swissmedic D11AC08 for 4300702 Squa-Med Medizinal Shampoo liq pH 5
WARNING: ATC differs from refdata J01XD03 and swissmedic P01AB03 for 4306501 TIBERAL Inf Konz 500 mg/3ml 5 Amp 3 ml
WARNING: ATC differs from refdata R06AA02 and swissmedic A04A for 4319403 Trawell 20 mg, Kaugummi-Dragées
WARNING: ATC differs from refdata D08AG02 and swissmedic D08AX05 for 4346801 BRAUNODERM Alkoholische Lös farbl Fl 1000 ml
WARNING: ATC differs from refdata D08AG02 and swissmedic D08AX05 for 4346802 BRAUNODERM Alkoholische Lös gefärb 10 Fl 1000 ml
WARNING: ATC differs from refdata C01EB04 and swissmedic C01EX for 4363001 Cardiodyn Weissdorn, Tabletten
WARNING: ATC differs from refdata B05XC and swissmedic V06DX for 4367902 VITALIPID N Adult Inf Emuls 10 Zus Amp 10 ml
WARNING: ATC differs from refdata B05XC and swissmedic V06DX for 4367901 VITALIPID N Infant Inf Emuls 10 Zus Amp 10 ml
WARNING: ATC differs from refdata D02AX and swissmedic D03AX for 4377001 KELOSOFT Narbencreme 10 g
WARNING: ATC differs from refdata D03AX03 and swissmedic D08AC52 for 4389101 BEPANTHEN Plus Creme 5 % 4 Tb 3.5 g
WARNING: ATC differs from refdata C05BA53 and swissmedic M02AX10 for 4399601 Keppur Salbe
WARNING: ATC differs from refdata R05 and swissmedic R05DB20 for 4413602 Herbapect Bronchialpastillen, Pastillen
WARNING: ATC differs from refdata R03CC02 and swissmedic R03AC02 for 4439701 VENTOLIN Inj Lös 0.5 mg/ml 5 Amp 1 ml
WARNING: ATC differs from refdata R03CC02 and swissmedic R03AC02 for 4439702 VENTOLIN Inf Konz 5 mg/5ml 5 Amp 5 ml
WARNING: ATC differs from refdata R03CC05 and swissmedic G02CA for 4443801 GYNIPRAL Inj Lös 10 mcg/2ml 5 Amp 2 ml
WARNING: ATC differs from refdata C01EZ and swissmedic C01EX for 4503501 RECKEWEG R3 Corvosan Tropfen Fl 50 ml
WARNING: ATC differs from refdata G04CZ and swissmedic G04BX for 4505401 RECKEWEG R25 Prostatan Tropfen Fl 50 ml
WARNING: ATC differs from refdata A13AZ and swissmedic N05CX for 4507201 RECKEWEG R44 Hypotonol Tropfen Fl 50 ml
WARNING: ATC differs from refdata R02AZ and swissmedic R01AX10 for 4507301 RECKEWEG R45 Laryngin Tropfen Fl 50 ml
WARNING: ATC differs from refdata M09AZ and swissmedic M01AX for 4507401 RECKEWEG R46 Manurheumin Tropfen Fl 50 ml
WARNING: ATC differs from refdata C01EZ and swissmedic C01EX for 4508601 RECKEWEG R58 Vernadon Tropfen Fl 50 ml
WARNING: ATC differs from refdata A16AX99 and swissmedic A03AX for 4521402 Colpermin Kaps
WARNING: ATC differs from refdata D09AA09 and swissmedic D08AG02 for 4582701 BRAUNOVIDON Salbengaze 7.5x10cm
WARNING: ATC differs from refdata D01AC20 and swissmedic D07XA02 for 4586001 Imacort Creme
WARNING: ATC differs from refdata A12CC01 and swissmedic B05XA11 for 4588201 Magnesiumchlorid 0,5 molar B. Braun, Zusatzampulle für              Infusionslösungen
WARNING: ATC differs from refdata D08AG02 and swissmedic D08AG03 for 4669301 DESTROBAC wässrige Lösung 50 ml
WARNING: ATC differs from refdata D07XB05 and swissmedic D11AX11 for 4676901 PIGMANORM Creme
WARNING: ATC differs from refdata D02AC and swissmedic D11AX for 4693503 Excipial Balmandol Badeöl Lös
WARNING: ATC differs from refdata A13AZ and swissmedic A16 for 4707301 Bio-Magnesium Phytomed, homöopathische Tabletten
WARNING: ATC differs from refdata C05BA53 and swissmedic M02AX10 for 4712201 Keppur Gel
WARNING: ATC differs from refdata N02AJ06 and swissmedic N02BE51 for 4735301 Co Dafalgan Brausetabl 500/30mg
WARNING: ATC differs from refdata D01AC01 and swissmedic D10AX for 4742902 AKNECOLOR Crèmepaste getönt Tb 30 g
WARNING: ATC differs from refdata N05CX99 and swissmedic N05CM for 4771801 Valverde Entspannung, Filmtabletten
WARNING: ATC differs from refdata R06AA09 and swissmedic N05CM for 4773501 SANALEPSI N Tropfen Fl 50 ml
WARNING: ATC differs from refdata D04AB01 and swissmedic D03AX for 4773701 LEUCEN Brand-und Wundgel Tb 30 g
WARNING: ATC differs from refdata L04AX03 and swissmedic L01BA01 for 4775301 Methotrexat Farmos Tabl 2.500 mg
WARNING: ATC differs from refdata L04AX03 and swissmedic L01BA01 for 4775302 Methotrexat Farmos Tabl 10 mg
WARNING: ATC differs from refdata A01AB11 and swissmedic A01AD11 for 4915301 TENDERDOL Gel o Zucker Tb 20 g
WARNING: ATC differs from refdata A02AD01 and swissmedic A02AC10 for 4967002 Rennie Spearmint, Lutschtabletten
WARNING: ATC differs from refdata A06AB08 and swissmedic A06AB58 for 4979802 LAXASAN Tropfen Fl 20 ml
WARNING: ATC differs from refdata R05X and swissmedic A01AD11 for 5006801 ELIXAN MELALEUKA PUR Heilöl 20 ml
WARNING: ATC differs from refdata A01AZ and swissmedic A01AD11 for 5024501 CITROKEHL Inj Lös 10 Amp 2 ml
WARNING: ATC differs from refdata C01EB04 and swissmedic C01EX for 5035101 Zeller Herz und Nerven, Filmtabletten
WARNING: ATC differs from refdata B05BA10 and swissmedic B05BA01 for 5047804 AMINOMIX N 1 Inf Lös Biofine 4 Btl 1500 ml
WARNING: ATC differs from refdata D11AZ and swissmedic D11AX for 5088401 SIMILASAN Hautausschläge Glob 15 g
WARNING: ATC differs from refdata V03AE07 and swissmedic A12AA12 for 5097402 Calcium Ac Phosphatb Bichsel Kaps 400 mg
WARNING: ATC differs from refdata A01AA03 and swissmedic A01AA51 for 5122601 PARO Amin Fluor Gelée Frut 25 g
WARNING: ATC differs from refdata N02AJ06 and swissmedic N02BE51 for 5132101 Co Dafalgan Filmtabl 500/30mg
WARNING: ATC differs from refdata S01AE01 and swissmedic S01AX11 for 5135701 Floxal Gtt Opht 0.300 %
WARNING: ATC differs from refdata S01AE01 and swissmedic S01AX11 for 5135801 Floxal Augensalbe 0.300 %
WARNING: ATC differs from refdata D03AX03 and swissmedic D08AC52 for 5173901 BEPANTHEN Plus Microdos 30 ml
WARNING: ATC differs from refdata S01AE03 and swissmedic S01AX13 for 5189801 Ciloxan Gtt Opht
WARNING: ATC differs from refdata D01AE54 and swissmedic D04AX for 5200401 Pruri-Med Emuls
WARNING: ATC differs from refdata R06AA02 and swissmedic N05CM for 5203501 Bonox, Tabletten
WARNING: ATC differs from refdata R06AA02 and swissmedic N05CM for 5236501 Nardyl Sommeil, comprimés
WARNING: ATC differs from refdata A11AB and swissmedic A11AA03 for 5312101 Burgerstein Geriatrikum, Kapseln
WARNING: ATC differs from refdata A10AD01 and swissmedic A10AC30 for 5396201 Insulin Insuman Comb 25 Inj Susp Optipen
WARNING: ATC differs from refdata R02AA06 and swissmedic R02AA20 for 5403201 Lidazon citron, comprimés à sucer
WARNING: ATC differs from refdata R02AA06 and swissmedic R02AA20 for 5403301 Lidazon himbo, comprimés à sucer
WARNING: ATC differs from refdata C05CX03 and swissmedic C05CA for 5423802 Venostasin, Kapseln
WARNING: ATC differs from refdata A11AB and swissmedic A11AA03 for 5426902 Fortevital, Kapseln
WARNING: ATC differs from refdata V04CX and swissmedic S01JA01 for 5460403 FLUORESCEINE Faure Inj Lös 10 % 10 Amp 5 ml
WARNING: ATC differs from refdata N05CX99 and swissmedic N05CM for 5467701 Relaxane Filmtabl
WARNING: ATC differs from refdata R05CB10 and swissmedic R02AB02 for 5469701 Solmucaine, compresse da sciogliere in bocca
WARNING: ATC differs from refdata G03FB05 and swissmedic G03FA01 for 5471601 Systen Sequi Matrixpfl
WARNING: ATC differs from refdata N01BB02 and swissmedic D04AB01 for 5474601 Neurodol Tissugel Pfl
WARNING: ATC differs from refdata A10AD04 and swissmedic A10AB04 for 5476201 Humalog Mix 25 Inj Susp f Pen
WARNING: ATC differs from refdata A10AD04 and swissmedic A10AB04 for 5476301 Humalog Mix 50 Inj Susp f Pen
WARNING: ATC differs from refdata V01AA20 and swissmedic V01AA05 for 5478701 Alk7 Frühblühermischung Inj Susp A+B
WARNING: ATC differs from refdata V01AA20 and swissmedic V01AA05 for 5478702 Alk7 Frühblühermischung Inj Susp B
WARNING: ATC differs from refdata A11AB and swissmedic A11AA03 for 5486501 FORTEVITAL Tonikum Fl 500 ml
WARNING: ATC differs from refdata A11GB99 and swissmedic A16AA for 5518101 Revitalose C 1000, Granulat
WARNING: ATC differs from refdata N06AX12 and swissmedic N07BA for 5526301 Zyban Ret Tabl 150 mg
WARNING: ATC differs from refdata S01XA12 and swissmedic S01XA20 for 5534001 Siccaprotect Gtt Opht
WARNING: ATC differs from refdata S01AE01 and swissmedic S01AX11 for 5538301 Floxal UD Gtt Opht 0.300 %
WARNING: ATC differs from refdata M02AA99 and swissmedic M02AX10 for 5560801 Assan Emgel
WARNING: ATC differs from refdata A11AB and swissmedic A11AA03 for 5570101 Burgerstein TopVital, Kapseln
WARNING: ATC differs from refdata A10AD05 and swissmedic A10AD01 for 5575702 Insulin NovoMix 30 FlexPen Inj Susp Fertigpen
WARNING: ATC differs from refdata A06AC55 and swissmedic A06AB56 for 5585102 Linomed Gran
WARNING: ATC differs from refdata M02A and swissmedic M02AX10 for 5597301 CHINAMED Emuls Tb 100 ml
WARNING: ATC differs from refdata S01AE03 and swissmedic S01AX13 for 5598201 Ciloxan Augensalbe
WARNING: ATC differs from refdata J05AP01 and swissmedic J05AB04 for 5600101 Copegus Tabl 200 mg
WARNING: ATC differs from refdata J05AP01 and swissmedic J05AB04 for 5600102 Copegus Tabl 400 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620602 Helixor A Inj Lös 0.100 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620603 Helixor A Inj Lös 1 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620604 Helixor A Inj Lös 5 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620605 Helixor A Inj Lös 10 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620606 Helixor A Inj Lös 20 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620607 Helixor A Inj Lös 30 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620608 Helixor A Inj Lös 50 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620609 Helixor Inj Lös 100 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620702 Helixor M Inj Lös 0.100 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620703 Helixor M Inj Lös 1 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620704 Helixor M Inj Lös 5 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620705 Helixor M Inj Lös 10 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620706 Helixor M Inj Lös 20 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620707 Helixor M Inj Lös 30 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620708 Helixor M Inj Lös 50 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620709 Helixor M Inj Lös 100 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620802 Helixor P Inj Lös 0.100 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620803 Helixor P Inj Lös 1 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620804 Helixor P Inj Lös 5 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620805 Helixor P Inj Lös 10 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620806 Helixor P Inj Lös 20 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620807 Helixor P Inj Lös 30 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620808 Helixor P Inj Lös 50 mg
WARNING: ATC differs from refdata L01CZ and swissmedic L01CX for 5620809 Helixor P Inj Lös 100 mg
WARNING: ATC differs from refdata H03BA02 and swissmedic H03BB02 for 5630001 Propycil Tabl 50 mg
WARNING: ATC differs from refdata N05AD08 and swissmedic N01AX01 for 5655002 DROPERIDOL Sintetica Inj Lös 1 mg/2ml 10 Amp 2 ml
WARNING: ATC differs from refdata V03AE07 and swissmedic A12AA12 for 5759102 Renacet Filmtabl 950 mg
WARNING: ATC differs from refdata V04CJ01 and swissmedic H01AB01 for 5768701 Thyrogen Trockensub 0.900 mg
WARNING: ATC differs from refdata R05X and swissmedic R02A for 5775101 Echinarom Halsschmerzen Tabl
WARNING: ATC differs from refdata A01AD11 and swissmedic R02AX for 5833601 VOGEL Halsschmerz-Spray 30 ml
WARNING: ATC differs from refdata L04AX03 and swissmedic L01BA01 for 5837001 Methotrexat Sandoz Tabl 5 mg
WARNING: ATC differs from refdata L04AX03 and swissmedic L01BA01 for 5837002 Methotrexat Sandoz Tabl 10 mg
WARNING: ATC differs from refdata N07CA52 and swissmedic N07CA02 for 5928501 Arlevert Tabl
WARNING: ATC differs from refdata A10AD04 and swissmedic A10AB04 for 5935501 Humalog Mix 25 KwikPen Inj Susp
WARNING: ATC differs from refdata A10AD04 and swissmedic A10AB04 for 5935601 Humalog Mix 50 KwikPen Inj Susp
WARNING: ATC differs from refdata R05DA04 and swissmedic R05FA02 for 6054001 CODICALM Sirup 5 mg/5ml 200 ml
WARNING: ATC differs from refdata V01AA20 and swissmedic V01AA05 for 6069501 Alutard SQ Frühblühermischung Inj Susp Anf Be
WARNING: ATC differs from refdata V01AA20 and swissmedic V01AA05 for 6069504 Alutard SQ Frühblühermischung Inj Susp Fortsetz Be
WARNING: ATC differs from refdata D04AB01 and swissmedic D04AX for 6080901 FENIPIC plus Gel Tb 24 g
WARNING: ATC differs from refdata D04AB01 and swissmedic D04AX for 6081001 FENIPIC plus Lös Roll-on 8 ml
WARNING: ATC differs from refdata M09AB03 and swissmedic B06AA11 for 6223001 Bromelain Zentiva Drag 26 mg
WARNING: ATC differs from refdata R02AA21 and swissmedic D08AJ57 for 6280901 OCTENIMED Gurgellösung Fl 250 ml
WARNING: ATC differs from refdata R06AE09 and swissmedic R06AE07 for 6292001 Levocetirizin Spirig HC Filmtabl 5 mg
WARNING: ATC differs from refdata R05FB02 and swissmedic R05DB20 for 6295901 Pectus Junior Hustenpastillen für Kinder mit Vitamin C, Pastillen
WARNING: ATC differs from refdata C05BA53 and swissmedic M02AX10 for 6299001 TRAUMALIX DOLO venactiv Salbe 40 g
WARNING: ATC differs from refdata C01EB04 and swissmedic C01EX for 6299201 Kardionin Filmtabl
WARNING: ATC differs from refdata R05FB02 and swissmedic R05CA10 for 6303701 GEM Bronchial-Pastillen Mint
WARNING: ATC differs from refdata R05CA10 and swissmedic R05X for 6327601 SIDROGA Brust- und Hustentee N 20 Btl 2 g
WARNING: ATC differs from refdata A13A and swissmedic C01EX for 6511701 Irogerin, Dragées
WARNING: ATC differs from refdata A13A and swissmedic C01EX for 6514701 Geroviton, Dragées
WARNING: ATC differs from refdata R05FB02 and swissmedic R05DB20 for 6529501 Coop Vitality Bronchialpastillen Junior, Pastillen
WARNING: ATC differs from refdata J05AP07 and swissmedic J05AX14 for 6533201 Daklinza 30 mg, Filmtabletten
WARNING: ATC differs from refdata J05AP07 and swissmedic J05AX14 for 6533202 Daklinza 60 mg, Filmtabletten
WARNING: ATC differs from refdata N02BE01 and swissmedic N02BE51 for 6552401 Dolo-Kranit, Tabletten
WARNING: ATC differs from refdata R05CA10 and swissmedic R05X for 6558501 HELENA'S Erkältungstee 20 Btl 1.5 g
WARNING: ATC differs from refdata A16AX99 and swissmedic A15 for 6558801 HELENA'S Magentee 20 Btl 1 g
WARNING: ATC differs from refdata R06AA02 and swissmedic N05CM for 6583701 Coop Vitality Diphenhydramin, Tabletten
WARNING: ATC differs from refdata A10BJ03 and swissmedic A10BX10 for 6596801 Lyxumia Inj Lös 1x10 mcg/1x20 mcg Fertpen
WARNING: ATC differs from refdata A02BC05 and swissmedic A02BC01 for 6632101 Esoprax Filmtabl 20 mg
WARNING: ATC differs from refdata A02BC05 and swissmedic A02BC01 for 6632102 Esoprax Filmtabl 40 mg
WARNING: ATC differs from refdata J05AG01 and swissmedic J05AB01 for 6648301 Nevirapin Sandoz Ret Tabl 400 mg
WARNING: ATC differs from refdata L04AA40 and swissmedic L01BB04 for 6683101 MAVENCLAD Tabl 10 mg
WARNING: ATC differs from refdata R06AA02 and swissmedic N05CM for 6706101 Amavita Dormyl-N 50 mg, Tabletten
<pre>

**Comment by zdavatz** [comment]
Ich melde es gleich der Swissmedic. Zur Zeit werden zu wenig Public Domain Daten validiert. Das werden wir ändern.

**Comment by zdavatz** [comment]
reported: https://slack-files.com/T27F6280H-FJ5NL0XUP-a6fe006518

**Comment by zdavatz** [comment]
Antwort Swissmedic: https://ywesee.slack.com/files/U27FC8WLA/FJA4GE561/fwd__wg__broncho-vaxom_hat_in_im_packiungen.xlsx__00667_einen_anderen_atc-code_als_in_der_fi
