### ISSUE TITLE
replace epha download link

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb2xml#33]
replace epha download link with 
DE: http://pillbox.oddb.org/drug_interactions_csv_de.zip
FR: http://pillbox.oddb.org/drug_interactions_csv_fr.zip

**Comment by ngiger** [comment]
But here we have many changes. The old format from https://download.epha.ch/cleaned/matrix.csv was:
> "ATC1","Name1","ATC2","Name2","Info","Mechanismus","Effekt","Massnahmen","Grad"
"N06AB06","Sertralin","M03BX02","Tizanidin","Keine Interaktion","Tizanidin wird über CYP1A2 metabolisiert. Sertralin beeinflusst CYP1A2 jedoch nicht.","Keine Interaktion.","Die Kombination aus Sertralin und Tizanidin hat kein bekanntes Interaktionspotential.","A"

The new one from http://pillbox.oddb.org/drug_interactions_csv_de.zip has no header and the first line contains HTML element
<pre>
</D01BA02||N02AX02||<div><div class="paragraphD" id="D01BA02-N02AX02"><div class="absTitle">D01BA02 [Terbinafin] &rarr; N02AX02 [Tramadol]</div></div><p class="spacing2"><i>Risikoklasse:</i> Kombination vermeiden (D)</p><p class="spacing2"><i>Möglicher Effekt:</i> Verminderte analgetische Wirkung</p><p class="spacing2"><i>Mechanismus:</i> Terbinafin hemmt CYP2D6  und damit auch den Metabolismus von Tramadol.</p><p class="spacing2"><i>Empfohlene Massnahmen:</i> Der gleichzeitige Einsatz von Tramadol und Terbinafin ist ungünstig. Es sollte eine andere analgetische Therapie gewählt oder beispielsweise Itraconazol als alternatives Antimykotikum eingesetzt werden.</p></div>
</pre>

**Comment by zdavatz** [comment]
I will commit the old epha File to oddb2xml_files

**Comment by zdavatz** [comment]
Neuer Download Link: https://github.com/zdavatz/oddb2xml_files/blob/master/interactions_de_utf8.csv

**Comment by zdavatz** [comment]
should be done with: 5b3bf412f1fc306d5d2c9705c16f14c9b9940459

**Comment by zdavatz** [comment]
Version 2.6.2 still gives one Error:
```
  inflating: /tmp/downloads/transfer.dat  
/home/zeno/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect': Failed to open TCP connection to download.epha.ch:80 (getaddrinfo: Name or service not known) (SocketError)
```

**Comment by zdavatz** [comment]
für das atc.csv bitte neu dieses File verwenden: [atc_codes_multi_lingual.txt](https://github.com/zdavatz/cpp2sqlite/blob/master/input/atc_codes_multi_lingual.txt)

**Comment by ngiger** [comment]
Should be fixed with commit 

* https://github.com/ngiger/oddb2xml/commit/892112c370c70f375fdc7b5755a67ce5e9def65a

oddb2xml -e finished without problems. oddb2xml --artikelstamm is currently running locally

**Comment by zdavatz** [comment]
Kannst Du noch das neue Gem releasen bitte.

**Comment by zdavatz** [comment]
oddb2xml-2.6.3.gem has been released.
