### ISSUE TITLE
Varilrix wird nicht als Impfstoff erkannt

### ISSUE THREAD

**Issue by ngiger** [zdavatz/oddb2xml#35]
Gemäss Medelexis (Mathej Djuranec) fehlt beim Artikel 7680005850010 das zugehörende Produkt mit dem ATC-Code.

**Comment by zdavatz** [comment]
Schaue ich mir gleich an.

**Comment by ngiger** [comment]
Ich habe lokal schon einen Fix dafür.

**Comment by zdavatz** [comment]
ok, wo liegt das Problem?

**Comment by zdavatz** [comment]
wie heisst das Produkt?

**Comment by ngiger** [comment]
Die Produkt-Nummer/ATC wurde nicht immer richtig gesetzt, da sie entweder aus refdata oder swissmedic kommen können.

**Comment by ngiger** [comment]
Meines Erachtens gibt es hier eine Inkonsistenz zwischen den Einträgen im Packungen.xlsx wo für die IKSNR 00585 folgendes angegeben wird:

* Dosierstärke akq Sequenz-Nummer: 1
* Name: Varilrix, Pulver und Lösungsmittel zur Herstellung einer Injektionslösung
* Packungs-Code 003

Daraus ergibt sich ein GTIN: 7680005850034. Aber in refdata_Pharma.xml findet man nur folgende Angaben:
<pre>
      <ITEM DT="2018-12-05T00:00:00">
        <ATYPE>PHARMA</ATYPE>
        <GTIN>7680005850010</GTIN>
        <PHAR>1770177</PHAR>
        <SWMC_AUTHNR>00585001</SWMC_AUTHNR>
        <NAME_DE>VARILRIX Trockensub c Solv Fertspr 0.5 ml</NAME_DE>
        <NAME_FR>VARILRIX subst sèche c solv ser pré 0.5 ml</NAME_FR>
        <ATC>J07BK01</ATC>
        <AUTH_HOLDER_NAME>GlaxoSmithKline AG</AUTH_HOLDER_NAME>
        <AUTH_HOLDER_GLN>7601001000674</AUTH_HOLDER_GLN>
      </ITEM>
</pre>

Kannst Du schauen, dass refdata den Fehler korrigiert?

**Comment by zdavatz** [comment]
Danke, Emails an Refdata und BAG sind raus: https://slack-files.com/T27F6280H-FMF8Z4B9V-cdbe16fedc

**Comment by zdavatz** [comment]
Ich denke, Du solltest beide GTINs übernehmen, den einen mit Preis den anderen ohne. Das machen wir bei AmiKo/oddb2xml auch so. https://slack-files.com/T27F6280H-FM22FFMAP-05624fa121

**Comment by ngiger** [comment]
Neues Gem-Version 2.6.4 erstellt
