### ISSUE TITLE
Update BAG Download Link

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb2xml#37]
siehe https://github.com/zdavatz/oddb.org/issues/96

Der Download Link vom BAG hat geändert.

**Comment by ngiger** [comment]
Wenn man auf http://www.spezialitätenliste.ch/ dem link IT-70 -> https://bag.hcisolutions.ch/Sl2007.web.external/varia_De.htm zu folgen versucht, gibt es einen Fehler 404.
BItte dieses Problem melden. Wo kann man neu diese Datei herholen?

**Comment by zdavatz** [comment]
Email ist raus: https://slack-files.com/T27F6280H-FSK4WN9PW-d5851f7f60

**Comment by ngiger** [comment]
Rubygem oddb2xml Version 2.6.5 released. Option --artikelstamm führt zu Fehlern, das varia_De.hml für die Kapitel 70-Items nicht runtergeladen werden kann.

**Comment by zdavatz** [comment]
der neue Link lautet: http://www.spezialitaetenliste.ch/varia_De.htm

**Comment by ngiger** [comment]
Rubygem oddb2xml Version 2.6.6 released.

**Comment by zdavatz** [comment]
Danke!
