### ISSUE TITLE
Pectocalmine mit falscher Abgabekategorie C

### ISSUE THREAD

**Issue by ngiger** [zdavatz/oddb2xml#39]
Gemäss https://de.wikipedia.org/wiki/Abgabekategorie#Kategorie_C_(historisch,_Abgabe_nach_Fachberatung_durch_Medizinalpersonen)
 ist die Abgabekategorie C nicht mehr erlaubt.

Im aktuellen Builde von oddb2xml --artikelstamm tauchen jedoch 2 Hustensirupe Pectocalmine mit dieser Kategorie auf, welche aus der Datei refdata_pharma.xml stammen

**Comment by zdavatz** [comment]
Refdata führt keine Kategorie-Angaben.

**Comment by zdavatz** [comment]
Gemäss Swissmedic ist der immer noch Liste C.
![Bildschirmfoto 2020-06-03 um 11 19 17](https://user-images.githubusercontent.com/4953/83619401-1c7a4100-a58c-11ea-895e-0bef5880fe23.png)
