### ISSUE TITLE
Ruby 2.4.0 Error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb2xml#40]
Release `2.6.7` breaks usage for `Ruby-2.4.0`. 
```
/opt/ywesee/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/oddb2xml-2.6.7/lib/oddb2xml/downloader.rb:286:in `initialize': private method `open' called for URI:Module (NoMethodError)
        from /opt/ywesee/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/oddb2xml-2.6.7/lib/oddb2xml/cli.rb:202:in `new'
        from /opt/ywesee/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/oddb2xml-2.6.7/lib/oddb2xml/cli.rb:202:in `download'
        from /opt/ywesee/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/oddb2xml-2.6.7/lib/oddb2xml/cli.rb:56:in `run'
        from /opt/ywesee/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/oddb2xml-2.6.7/bin/oddb2xml:38:in `<top (required)>'
        from /opt/ywesee/.rbenv/versions/2.4.0/bin/oddb2xml:22:in `load'
        from /opt/ywesee/.rbenv/versions/2.4.0/bin/oddb2xml:22:in `<main>'
```

**Comment by ngiger** [comment]
Mein zwei commits  machen, dass alle Tests auch für Ruby 2.4 laufen.
Gemäss https://travis-ci.org/github/ngiger/oddb2xml/builds/702302067
schlagen sie jedoch für Ruby 2.2 und Ruby 2.3 fehl.
Wäre es okay als minimale Ruby-Version 2.4 anstelle von 2.2 im gemspec einzutragen?

**Comment by ngiger** [comment]
Bin auch dabei für den Artikelstamm noch einen Patch zu machen, dass für mind. zwei Impfstoffe (Varilrix 7680005850010 und 7680660370014 Menjugate Liquid Inj Susp Fertspr 0.500 ml ) die ATC-Code richtig gesetzt und auf ein vorhandenen Product (aka Sequenz) verwiesen wird, auch wenn für diese Packungscodes keine Einträge im Packungen.XLSX vorhanden sind.

**Comment by zdavatz** [comment]
Ja, `Ruby-2.4.0` genügt.

**Comment by zdavatz** [comment]
done with  55d04b3ff09ed0d21e1b4a2c0ceba2559cfa0cda - thank you @ngiger
