### ISSUE TITLE
Rockethealth kann Artikelstamm v5 oddb2xml wegen Chapter70_HACK Element nicht einlesen

### ISSUE THREAD

**Issue by ngiger** [zdavatz/oddb2xml#44]
Julian Kappis hat dieses Problem von Rocketchat gemeldet bekommen.

Meines Erachtens können wir ohne Probleme zu generieren, dieses Element wieder ausbauen und nur den Kommentar  drin lassen.

**Comment by zdavatz** [comment]
Interessant, Danke für die Info.

**Comment by zdavatz** [comment]
können wir das schliessen? Aktualisierst Du noch das Gem?

**Comment by ngiger** [comment]
Habe von Julian noch keinen Bescheid bekommen, ob die neue Datei von der Rockethealth Applikation ohne Probleme geladen wird.

**Comment by zdavatz** [comment]
Danke für die Info.

**Comment by ngiger** [comment]
Gemäss Julian konnte Rockethealth den Artikelstamm vom November ohne Probleme einlesen.
Werde jetzt dann alles für die Version 2.7.0 vorbereiten

**Comment by ngiger** [comment]
Release 2.7.0 was created on November 2020
