### ISSUE TITLE
Refdata XML files without pharmacode

### ISSUE THREAD

**Issue by ngiger** [zdavatz/oddb2xml#45]
Refdata no longer published the pharmacode field.
Building the artikelstamm failed, because it failed the validation with errors like `artikelstamm_01022021_v5.xml:1693969: element PHAR: Schemas validity error : Element '{http://elexis.ch/Elexis_Artikelstamm_v5}PHAR': '' is not a valid value of the local atomic type.`

**Comment by zdavatz** [comment]
In case you still want the pharmacode, you can grab from the transfer.dat.

**Comment by ngiger** [comment]
Matej und Julian werden den Build unter https://artikelstamm.elexis.info/v5/20210201/artikelstamm_01022021_v5.xml testen und schauen, ob er für die Medelexis okay ist.

**Comment by ngiger** [comment]
Gemäss Julian&Mathej ist der gestern erzeugte Artikelstamm für die Medelexis okay.

**Comment by ngiger** [comment]
Werde einen Release 2.7.1 erst machen, wenn das Problem mit den NBR_PRODUCTS gelöst ist.

**Comment by ngiger** [comment]
Mathej and Julian want to add the pharmacode from transfer.dat if possible, as many of the consumers of invoices produced by Elexis do not accept GTINs, but still want the pharmacodes.

**Comment by ngiger** [comment]
Was okay for Mathe
