### ISSUE TITLE
Pharmacode nicht mehr vorhanden bei Refdata.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb2xml#46]
Ich lade alle zwei Monate die oddb_product.xml und oddb_article.xml in meine Datenbank. Nun ist mir aufgefallen, dass seit meinem letzten Import die xml-Struktur leicht geändert wurde bei product.xml. 

In der heutigen Ausgabe von product.xml (02.02.2021) fehlt die Entität <RESULT>, wie Sie aus der Abbildung sehen können. Das ist bei früheren xml und auch in der aktuellen article.xml nicht der Fall. Die Entität <RESULT> enthält die Anzahl Records >NBR_RECORD>, die ich als Kontrolle verwende.
 
![feeback_fabio_valeri](https://user-images.githubusercontent.com/4953/106638089-c2e76d80-6583-11eb-99e0-9d48dc379f6a.jpg)

Ich kann damit leben, aber ich wollte sie einfach darüber informieren, dass doch eine wichtige Kontrolle nicht mehr vorhanden ist. Ich weiss nicht, seit wann das der Fall ist, aber ich könnte es herausfinden, falls erwünscht. Wenn Sie es so belassen wollen, wie es nun ist, wäre ich Ihnen dankbar, wenn Sie mich informieren. Dann passe ich mein Import-Skript entsprechend an, damit keine Fehlermeldung stattfindet. 

Seit 06.01.2021 wird kein NBR_RECORD geliefert.
Bis 05.01.2021 wurde NBR_RECORD geliefert.

**Comment by ihmz-fabio** [comment]
Die Pharmacodes werden (in article.xml) immer noch geliefert, jedoch nicht mehr alle:
![grafik](https://user-images.githubusercontent.com/15674893/106718896-f1a42900-6601-11eb-8d98-8dcc33e7c525.png)
Die Anzahl Pharmacodes nimmt seit 2021 drastisch ab. Vor 2019 entsprach die Anzahl Records der Anzahl Pharmacodes.
Der Grund liegt wohl darin, dass der Pharmacode kontinuierlich abgeschafft wird und durch den GTIN ersetzt wird.
Daher denke ich nicht, dass der Pharmacode etwas mit dem fehlenden Eleent zu tun hat.

**Comment by zdavatz** [comment]
ok, Danke @ihmz-fabio. Mal schauen was @ngiger dazu sagt.

**Comment by ngiger** [comment]
Es gibt spec-Tests, welche testen ob das NBR_RECORD in diversen (aber nicht allen) *.xml vorhanden sind.
Darf ich wissen, wie genau der Aufruf von oddb2xml war? Dann gehe ich dem Problem nach.

**Comment by ihmz-fabio** [comment]
Ist das eine Anfrage an mich? Wenn ja, verstehe ich es nicht.

**Comment by ngiger** [comment]
[@ihmz-fabio](url): Ich möchte wissen, wie genau sie auf der Shell den Befehlt oddb2xml aufgerufen haben. Ohne Parameter oder mit welchen Parametern, z.B. `bundle exec ruby bin/oddb2xml --help.`

Falls Sie nur das Gem installiert haben, geben Sie bitte die Version an.

Falls Sie ein git clone gemacht haben, bitte angeben, auf welchem commit sie stehen.

**Comment by zdavatz** [comment]
@ngiger die Daten werden von [hier](http://download.hin.ch/download/oddb2xml/oddb_product.xml) runtergeladen. Der Aufruf ist der normale Aufruf:

**Comment by ngiger** [comment]
@ihmz-fabio: Okay. Da muss bei HIN beim Erstellen was schief gelaufen sein.[oddb_article.xml](http://download.hin.ch/download/oddb2xml/oddb_article.xml) enhält die NBR_RECORD-Entität, nicht jedoch die oddb_product.xml

Beide XML-Dateien wurden mit oddb2xml 2.7.0 vom 5.11.2020 erstellt.

Ich lasse den Build lokal bei mir laufen, um zu sehen, was passiert ist, z.B. ob die bei refdata fehlenden Pharmacodes zu einem Abbruch führen, der nicht als Fehler erkannt wird. Das wird allerdings ein, zwei Stunden dauern.

**Comment by ihmz-fabio** [comment]
Genau. Ich lade jeweils das zip-File von hier https://download.hin.ch/download/oddb2xml/oddb2xml.zip, entpacke es und lade die xml-Files oddb_article.xml und oddb_product.xml mit einem Perl-Skript in eine MariaDB-Datenbank. Unabhängig von dem vorgehen: das File oddb_article.xml enthält die Entität <RESULTS>, oddb_product.xml jedoch nicht. Habe das bemerkt, weil das Perl-Skript Fehlermeldungen ausgab. Kontrolliert habe ich es, indem ich das File geöffnet habe und angeschaut habe.

**Comment by zdavatz** [comment]
@ihmz-fabio brauchst Du den Pharmacode noch?

**Comment by ihmz-fabio** [comment]
Im Prinzip nein. Aber es werden bei uns immer noch medis geliefert ohne GTIN aber mit Pharmacode. Deshalb denke ich, dass ich es immer noch benötige.

**Comment by zdavatz** [comment]
> Im Prinzip nein. Aber es werden bei uns immer noch medis geliefert ohne GTIN aber mit Pharmacode. Deshalb denke ich, dass ich es immer noch benötige.

Ok, dann werden wir den Pharmacode soweit wie möglich belassen.

**Comment by ngiger** [comment]
Getting pharmacode from transfer.dat was easy.
The missing RESULT entity stems probably from the fact that I have some invalid entries, eg.
`element DSCRD: Schemas validity error : Element '{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}DSCRD': [facet 'maxLength'] The value has a length of '128'; this exceeds the allowed maximum length of '120'.`

**Comment by ngiger** [comment]
Using the nokogiri option huge as suggested in nokogiri bug 2187 solved the problem.
Released oddb2xml gem 2.7.1.
I hope that tomorrow the HIN will produce a correct oddb_product.xml, 13489 articles should have a pharmacode from Zur Rose.

**Comment by zdavatz** [comment]
@ihmz-fabio Bist Du zufrienden so?

**Comment by ihmz-fabio** [comment]
Perfekt! Besten Dank.
