### ISSUE TITLE
BRONCHO-VAXOM with wrong ATC-Code in artikelstamm

### ISSUE THREAD

**Issue by ngiger** [zdavatz/oddb2xml#48]
In refdata_pharma.xml we have
```<GTIN>7680005960016</GTIN>
<SWMC_AUTHNR>00596001</SWMC_AUTHNR>
<NAME_DE>BRONCHO-VAXOM Kaps Erw 10 Stk</NAME_DE>
<NAME_FR>BRONCHO-VAXOM caps adult 10 pce</NAME_FR>
<ATC>J07AX</ATC>```
But after running oddb2xml --artikelstamm we have in the csv

`7680005960016,BRONCHO-VAXOM Kaps Erw 10 Stk,Kapsel(n),Kapsel(n),18.02,27.80,0059601,R07AX,"haemophili influenzae lysatum, diplococci pneumoniae lysatum, klebsiellae pneumoniae et ozaenae lysatum, staphylococci aurei lysatum, streptococci pyogen. et viridantis lysatum, neisseriae catarrhalis lysatum",,03.05.0.,""`

Why did the ATC-Code change fom J07AX to R07AX?

**Comment by ngiger** [comment]
In the swissmedic packages xlsx file the IKSNR 596 and 597 have the wrong ATC-Code R07AX.
This should be reported to the BAG.
When building the artikelstamm I think we should show a warning when the ATC code from refdata and swissmedic differ.

**Comment by zdavatz** [comment]
I will report it.

**Comment by ngiger** [comment]
Found 941 differences between refdata and swissmedic_packages see [warnings.txt](https://github.com/zdavatz/oddb2xml/files/6063383/warnings.txt)

**Comment by ngiger** [comment]
Mir scheint auch, dass zumindest für dies beiden IKSNR refdata_pharma den falschen Wert anzeigt. Spreche nochmals mit Medelexis, warum sie ein Problem haben.

**Comment by zdavatz** [comment]
SAI is online: https://sai.refdata.ch/?isfv=true&zn=596

**Comment by ngiger** [comment]
Aber im refdata_Pharma.xml von heute findet man immer noch J07AX
```
<..>
<ARTICLE xmlns="http://refdatabase.refdata.ch/Article_out" CREATION_DATETIME="2021-03-11T18:36:21.7942148+01:00">
<..>
1684       <ITEM DT="2020-08-11T00:00:00">
1685         <ATYPE>PHARMA</ATYPE>
1686         <GTIN>7680005960016</GTIN>
1687         <SWMC_AUTHNR>00596001</SWMC_AUTHNR>
1688         <NAME_DE>BRONCHO-VAXOM Kaps Erw 10 Stk</NAME_DE>
1689         <NAME_FR>BRONCHO-VAXOM caps adult 10 pce</NAME_FR>
1690         <ATC>J07AX</ATC>
1691         <AUTH_HOLDER_NAME>OM Pharma SA</AUTH_HOLDER_NAME>
1692         <AUTH_HOLDER_GLN>7601001001220</AUTH_HOLDER_GLN>
1693       </ITEM>```

**Comment by zdavatz** [comment]
Also ist der ATC-Code in Refdata falsch.

**Comment by zdavatz** [comment]
The error has been forwarded to info@refdata.ch

**Comment by zdavatz** [comment]
Refdata schreibt:

> Bezüglich deinem E-Mail wegen dem ATC Code noch folgende Info. Der ATC-Code
> von Broncho-Vaxom wurde schon einmal Thematisiert (im 2019). Damals hat
> Swissmedic festgestellt, dass die ZI den falschen Code benutzt hat und sie
> diesen bei Gelegenheit anpassen müsse. Offenbar hat die "Gelegenheit" noch
> nicht stattgefunden. Wir werden das Thema ATC Code diese Woche noch
> prinzipiell mit Swissmedic thematisieren, da es über alle Datenbanken
> hinweggesehen Abweichungen gibt.

**Comment by ngiger** [comment]
Anbei die Liste bei meinem Run von heute, der die Differenzen zwischen Swissmedic und refdata_pharma.xml anzeigt
[atc_differenzen.txt](https://github.com/zdavatz/oddb2xml/files/6156078/atc_differenzen.txt)

**Comment by zdavatz** [comment]
Danke, ist weitergeleitet an Refdata.

**Comment by zdavatz** [comment]
Refdata schreibt:

> Vielen Dank für das Dokument. Wir haben die genau gleiche Analyse vorgenommen und werden diese mit Swissmedic besprechen.
> 
> Spätestens an der Fachbeiratssitzung werden wir über das Ergebnis informieren.
