### ISSUE TITLE
Präparat NaCl Bichsel mit "(alt)" Vermerk in ODDB, obwohl auf SL

### ISSUE THREAD

**Issue by luetm** [zdavatz/oddb2xml#50]
In der SL ist das Präparat mit GTIN `7612929030193` mit dem IT-Code `05.03.20.` zu finden. In der oddb_article.xml findet man das Präparat auch, jedoch mit dem Namen `NACL Bichsel Inf Lös 0.9 % 500ml PPF m Be (alt)`. 

Warum ist das genau "alt"? Ich sehe in der oddb_article.xml nur vergleichbar das `7612929501655 (NACL Bichsel Inf Lös 0.9 % 500ml PPF)`, welches jedoch nicht in der SL ist.

Wie kann man genau nachvollziehen, welches Präparat von welchem abgelöst wurde?

Vielen Dank & Gruss
luetm

**Comment by zdavatz** [comment]
Das Produkt sieht nicht nach einem Medikament aus, weil der GTIN nicht mit 7680 beginnt.

**Comment by zdavatz** [comment]
Ich frage bei Refdata mal nach.

**Comment by zdavatz** [comment]
@ngiger woher kommt dieser Name: `NACL Bichsel Inf Lös 0.9 % 500ml PPF m Be (alt)`

**Comment by zdavatz** [comment]
kommt vom transfer.dat.
