### ISSUE TITLE
`popen': No such file or directory -

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb2xml#52]
Bedeutet dieser Error, dass die Swissmedic Seite unten?
![latest-screenshot](https://user-images.githubusercontent.com/4953/112595223-662d6400-8e0a-11eb-9b95-42c32e26f5bd.png)

**Comment by zdavatz** [comment]
This seems to be working: `oddb2xml -a` locally, so maybe the Swissmedic Site is just down at midnight?

**Comment by zdavatz** [comment]
Why is `swissmedic_orphan.xlsx` and `swissmedic_package.xlsx` not saved into the Downloads directory?

**Comment by ngiger** [comment]
This error happens, when the URL to be opened is not reachable. We could retry after a few seconds, but I do not know whether the site is always offline for a few seconds or minutes. And waiting 10 minutes till emitting an error, is probably not what people execpt,  too.

**Comment by zdavatz** [comment]
This is the beginning of the script:
```
#!/bin/bash

source /opt/ywesee/.bash_profile

export HOME=/opt/ywesee
if [ -d $HOME/.rbenv ]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    fi
    $0.rb $*

## check for Update
gem install oddb2xml

#### Download Data via oddb2xml (45)
rm -Rf /opt/ywesee/oddb2xml/files
mkdir /opt/ywesee/oddb2xml/files
mkdir /opt/ywesee/oddb2xml/files/45
cd /opt/ywesee/oddb2xml/files/45
oddb2xml -e -I 45 -c zip
```

**Comment by zdavatz** [comment]
https://github.com/zdavatz/oddb2xml/commits/master

**Comment by zdavatz** [comment]
ja das musst rein:
```
Was sicher noch ein Fehler ist, dass im oddb2xml.gemspecfolgende Zeile zu finden ist: spec.required_ruby_version = ">= 2.2.0".
Soll ich das für die nächste Gem-Version auf 2.5.0 ändern? Eine neue Gem-Version nur deswegen finde ich fast überrissen.
```
das neue gem hätte gar nicht installiert werden dürfen.

**Comment by zdavatz** [comment]
related to this issue #54
