### ISSUE TITLE
swissmedic_orphan.xlsx and swissmedic_packages.xlsx not saved into the downloads dir. Why?

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb2xml#53]
Why is swissmedic_orphan.xlsx and swissmedic_package.xlsx not saved into the Downloads directory?

**Comment by ngiger** [comment]
Nobody complained before.Was an oversight when starting to  use the downloads directory.
Will fix it next monday.

**Comment by ngiger** [comment]
Also there was a call to cleanup_file to remove these files, stemming from my commit:
```
0ac3c6bcc9a95c296feeed34b67f718a1a929227
Author: Niklaus Giger <niklaus.giger@member.fsf.org>
Date:   Tue Jan 7 16:07:02 2014 +0100

Remove *.xls/x-Files after extraction
```

Fixed this problem locally. Do you want a new release?

**Comment by zdavatz** [comment]
Yes please.

**Comment by ngiger** [comment]
Pushed the release 2.7.3 to rubygems. Needed 1.25h to fix this issue.
