### ISSUE TITLE
No such file or directory @ rb_file_s_size

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb2xml#54]
1. Install Ruby 3.0.0
2. Run `oddb2xml -e -I 45 -c zip`
3. The following Error happens:
4. `No such file or directory @ rb_file_s_size - /opt/ywesee/oddb2xml/files/downloads/swissmedic_orphan.xlsx (Errno::ENOENT)`
5. [log_30.3.2021.txt](https://github.com/zdavatz/oddb2xml/files/6228376/log_30.3.2021.txt)

**Comment by ngiger** [comment]
Release new gem version 2.7.4.
Needed 1h to fix this issue.
