### ISSUE TITLE
Since 28.2.22 swissmedic_package.xlsx contains IKSCAT A+

### ISSUE THREAD

**Issue by ngiger** [zdavatz/oddb2xml#57]
In column "N" Abgabekategorie Packung" we had till february 2022 only the values "A", "B","C", "D" "E", in march we have about 200 items with "A+". This distinction is not nedded for the the artikelstamm as used in the Elexis app.Therefore we should simply truncate it to "A".

**Comment by zdavatz** [comment]
A+ has been there for a long time now. A+ means `Betäubungsmittel`. We need to keep this information in oddb2xml.

**Comment by ngiger** [comment]
https://de.wikipedia.org/wiki/Abgabekategorie says
"Arzneimittel, die ein [Betäubungsmittel-Rezept](https://de.wikipedia.org/wiki/Bet%C3%A4ubungsmittelrezept) erfordern, findet man auch manchmal als Kategorie A+ ausgewiesen."

However we did not find any drug with a "A+" in column N in the swissmedic_package.xlsx.

As Elexis_Artikelstamm_v5.xsd does not have "A+" as a valid IKSCAT value I propose the following:
* Patch the build to emit a "A" instead of "A+" to respect the XSD file 
  * publish a new oddb2xml version
* Once elexis is able to handle "A+" drop the change, update the  Elexis_Artikelstamm_v5.xsd  to a new version with "A+" as a valid IKSCAT value
  * publish a new oddb2xml version

**Comment by zdavatz** [comment]
Es gibt sehr viele mit [A+](https://www.swissmedic.ch/dam/swissmedic/de/dokumente/internetlisten/zugelassene_packungen_human.xlsx.download.xlsx/zugelassene_packungen_ham.xlsx) als Kategorie:
![D29B67A5-12C7-40BF-968F-EBC9F97B4EE8](https://user-images.githubusercontent.com/4953/157316328-0d1328ed-d2f8-47c9-a32b-7a4db9fe68a9.jpeg)

**Comment by ngiger** [comment]
Ja aber erst seit 4. Februar 2022! Vorher gab es keine einziges. Auf thinpower:
/var/www/oddb.org/data/xls/Packungen-2022.01.06.xlsx enthält kein Vorkommniss von A+
/var/www/oddb.org/data/xls/Packungen-2022.02.04.xlsx enthält viele Vorkommniss von A+

**Comment by zdavatz** [comment]
Ok, interessant! Das sind auf jeden Fall Betäubungsmittel.

**Comment by ngiger** [comment]
Julian hat gestern noch gemeldet, dass die oddb_article.xml ebenfalls A1+ enthalten.

Die von wget https://download.hin.ch/download/oddb2xml/oddb_article.xml runtergeladenene Datei validiert nicht.

oddb_article.xml:1436135: element SMCAT: Schemas validity error : Element '{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}SMCAT': [facet 'enumeration'] The value 'A+' is not an element of the set {'B', 'C', 'D', 'A', 'E'}.

Patch dafür folgt

**Comment by ngiger** [comment]
Works now fine
