### ISSUE TITLE
Derma2Go can not load XML `oddb_article.xml` anymore after PR 60

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb2xml#61]
1. Does the PR https://github.com/zdavatz/oddb2xml/pull/60
2. Have any effect on `oddb_article.xml`
3. This file worked: [derma2go.xml.tar.gz](https://github.com/zdavatz/oddb2xml/files/9599427/derma2go.xml.tar.gz)
4. The file [from today](https://download.hin.ch/download/oddb2xml/oddb_article.xml) does not work anymore: 
5. ![latest-screenshot](https://user-images.githubusercontent.com/4953/191037028-c6092302-bfbd-44e8-acf4-01332443e81a.png)
6. The FR description vanished!

**Comment by ngiger** [comment]
Unfortunately, I added the fields DSCRI /SYN1I to oddb_article and only emitted the DSCRF field when it was different from the DSCRD.
This should have only be done for the artikelstamm_v5
Will undo these changes.

**Comment by zdavatz** [comment]
And please release a new gem.

**Comment by ngiger** [comment]
Tests look good. Building an actual oddb_article.xml and checking againt derma2go before releasing gem

**Comment by zdavatz** [comment]
fix done with: https://github.com/zdavatz/oddb2xml/commit/187d07ad7813741d8c24e8ff789ed7f4bd51e7df
